### PR TITLE
add elixir to Makefile and to the stats

### PR DESCRIPTION
**Pull request by aryx**
test plan:
cd lang
./test-lang elixir
cd elixir
make stat

### Security

- [x] Change has no security implications (otherwise, ping the security team)

### CODE REVIEW

**Comment by aryx** [comment]
This will help a bit https://github.com/returntocorp/semgrep/issues/3698

**Comment by aryx** [comment]
@mjambon weird, I get this error in CI:
```
done
Generate parser in /home/user/ocaml-tree-sitter/lang/semgrep-grammars/src/semgrep-elixir/.
/home/user/ocaml-tree-sitter/lang/semgrep-grammars/src/tree-sitter-elixir/grammar.js:54
].flat();
  ^

TypeError: [["->","when","::","|","=>","&","=","^^^","//","**",".","@"],IN_MATCH_OPS,OR_OPS,AND_OPS,COMP_OPS,REL_OPS,ARROW_OPS,IN_OPS,CONCAT_OPS,ADD_OPS,MULT_OPS,UNARY_OPS].flat is not a function
    at Object.<anonymous> (/home/user/ocaml-tree-sitter/lang/semgrep-grammars/src/tree-sitter-elixir/grammar.js:54:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/user/ocaml-tree-sitter/lang/semgrep-grammars/src/semgrep-elixir/grammar.js:7:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
```
but I don't get it locally.

**Comment by emjin** [comment]
When this happened to me for semgrep, `opam update` and `opam upgrade` let me see the error in CI

**Comment by mjambon** [comment]
:man_shrugging: I don't know anything about this error. Sorry!

**Pull request merged**
