### PR TITLE
use latest kotlin

### PR DESCRIPTION
**Pull request by aryx**
### Security

- [x] Change has no security implications (otherwise, ping the security team)

### CODE REVIEW

**Comment by aryx** [comment]
Hmm, we have regressions on semgrep-rules with that update. Let me check first.

**Comment by aryx** [comment]
@mjambon looks like the CI does not use the semgrep-specific scanner.c I provided. It's weird because it works locally.

**Review by colleend — APPROVED** [review]
lgtm! wierd that CI doesn't use scanner.c

**Comment by mjambon** [comment]
@pad ok, what you did to provide your own `scanner.c` makes sense. I don't know if there's a better solution. It's the first time we do this.

**Review by mjambon — APPROVED** [review]

**Pull request merged**
